### ISSUE TITLE
lost_battalionZ.sqf Error

### ISSUE THREAD

**Issue by canuckbrian** [redned70/DMSBanditMissions#1]
Line 150, "_missionName = "Stolen Virus;" is missing a " before the ; at the end

`// Define mission name (for map marker and logging)
_missionName = "Stolen Virus;
// Create Markers
_markers =`

Should be...

`// Define mission name (for map marker and logging)
_missionName = "Stolen Virus";
// Create Markers
_markers =`

**Comment by redned70** [comment]
thanks, fixed the missing quote.
